import streamlit as st
from backend.eda_utils import (
    rental_over_time_chart,
    revenue_by_store_chart,
    top_movies_df,
    city_options,
    date_options
)

st.set_page_config(page_title="EDA - Movie Recommender", layout="wide")

st.title("📊 Exploratory Data Analysis")

# Sidebar for filters
st.sidebar.header("Filter Options")
all_cities = city_options()
selected_cities = st.sidebar.multiselect("Select Store(s)", options=all_cities, default=all_cities)

min_date, max_date = date_options()
selected_dates = st.sidebar.slider(
    "Select Date Range",
    min_value=min_date,
    max_value=max_date,
    value=(min_date, max_date)
)

# Tabs for charts
tab1, tab2, tab3 = st.tabs(["Rentals Over Time", "Revenue by Store", "Top Movies"])

with tab1:
    st.subheader("Rentals Over Time")
    st.markdown(
        "See how the number of rentals changes over time for the selected stores."
    )
    rental_over_time_chart(selected_cities, selected_dates)

with tab2:
    st.subheader("Revenue by Store")
    st.markdown(
        "Revenue generated by each store during the selected period."
    )
    revenue_by_store_chart(selected_cities, selected_dates)

with tab3:
    st.subheader("Top Movies per Store")
    st.markdown(
        "Explore the most rented movies for the selected stores and date range."
    )
    top_movies_df(selected_cities, selected_dates)
